name: iranian_pro_vpn
description: A Smart VPN Application with Subscription Management.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  http: ^1.2.2
  percent_indicator: ^4.2.3
  url_launcher: ^6.3.0
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  matcher: ^0.12.18

flutter:
  uses-material-design: true